import StoryblokBridgeLoader from '@storyblok/react/bridge-loader';
import { apiPlugin, storyblokInit } from '@storyblok/react/rsc';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import Feature from '@/components/Feature';
import FormCheckbox from '@/components/Form/FormCheckbox';
import FormInput from '@/components/Form/FormInput';
import FormTextarea from '@/components/Form/FormTextarea';
import FormWrapper from '@/components/Form/FormWrapper';
import Grid from '@/components/Grid';
import Page from '@/components/Page';
import Teaser from '@/components/Teaser';

storyblokInit({
	accessToken: process.env.STORYBLOK_ACCESS_TOKEN,
	use: [apiPlugin],
  components: {
    feature: Feature,
    grid: Grid,
    page: Page,
    teaser: Teaser,
    FormWrapper: FormWrapper,
    FormInput: FormInput,
    FormTextarea: FormTextarea,
    FormCheckbox: FormCheckbox
  }
});

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>{children}</body>
			<StoryblokBridgeLoader options={{}} />
		</html>
	);
}
